export const queueTypes = [
  {
    queueId: 72,
    map: "Howling Abyss",
    description: "1v1 Snowdown Showdown games",
    notes: null,
  },
  {
    queueId: 73,
    map: "Howling Abyss",
    description: "2v2 Snowdown Showdown games",
    notes: null,
  },
  {
    queueId: 75,
    map: "Summoner's Rift",
    description: "6v6 Hexakill games",
    notes: null,
  },
  {
    queueId: 76,
    map: "Summoner's Rift",
    description: "Ultra Rapid Fire games",
    notes: null,
  },
  {
    queueId: 78,
    map: "Howling Abyss",
    description: "One For All: Mirror Mode games",
    notes: null,
  },
  {
    queueId: 325,
    map: "Summoner's Rift",
    description: "All Random games",
    notes: null,
  },
  {
    queueId: 400,
    map: "Summoner's Rift",
    description: "5v5 Draft Pick games",
    notes: null,
  },
  {
    queueId: 420,
    map: "Summoner's Rift",
    description: "5v5 Ranked Solo games",
    notes: null,
  },
  {
    queueId: 430,
    map: "Summoner's Rift",
    description: "5v5 Blind Pick games",
    notes: null,
  },
  {
    queueId: 440,
    map: "Summoner's Rift",
    description: "5v5 Ranked Flex games",
    notes: null,
  },
  {
    queueId: 450,
    map: "Howling Abyss",
    description: "5v5 ARAM games",
    notes: null,
  },
  {
    queueId: 700,
    map: "Summoner's Rift",
    description: "Clash games",
    notes: null,
  },
  {
    queueId: 820,
    map: "Twisted Treeline",
    description: "Co-op vs. AI Beginner Bot games",
    notes: null,
  },
  {
    queueId: 830,
    map: "Summoner's Rift",
    description: "Co-op vs. AI Intro Bot games",
    notes: null,
  },
  {
    queueId: 840,
    map: "Summoner's Rift",
    description: "Co-op vs. AI Beginner Bot games",
    notes: null,
  },
  {
    queueId: 850,
    map: "Summoner's Rift",
    description: "Co-op vs. AI Intermediate Bot games",
    notes: null,
  },
  {
    queueId: 2000,
    map: "Summoner's Rift",
    description: "Tutorial 1",
    notes: null,
  },
  {
    queueId: 1020,
    map: "Summoner's Rift",
    description: "One for All games",
    notes: null,
  },
  {
    queueId: 2010,
    map: "Summoner's Rift",
    description: "Tutorial 2",
    notes: null,
  },
  {
    queueId: 2020,
    map: "Summoner's Rift",
    description: "Tutorial 3",
    notes: null,
  },
];